FROM python:3.11-slim

RUN pip install --no-cache-dir datasette psycopg2-binary datasette-psycopg

EXPOSE 8080

CMD ["sh", "-c", "datasette --host 0.0.0.0 --port 8080 --setting sql_time_limit_ms 10000 --setting max_returned_rows 2000"]
